package com.youtube.central.models;

import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

import java.time.LocalDateTime;
import java.util.List;


@Setter
@AllArgsConstructor
@NoArgsConstructor
@ToString
@Entity
@Table(name="videos")
public class Video {
    @Id //This is id will generated by fiebase
    String id;//This id will get generatred inside firebase
    String description;
    LocalDateTime uploadDateTime;
    LocalDateTime updatedAt;
    String videoLink;
    String thumnailLink;
   @OneToMany
   List<Tag> tags;

}
